/**
 * Shell 补全脚本生成 —— `atr completion <shell>` 用
 *
 * 由用户自己决定怎么装(打到 ~/.zshrc / ~/.bashrc / ~/.config/fish/...),
 * 我们只 emit 脚本内容到 stdout。这样:
 *  - 不侵入用户 shell config(对比 tabtab 的 install 行为)
 *  - 失败可见(用户能看到脚本内容,自己决定怎么处理)
 *  - 易卸载(用户记得删哪一段)
 *
 * 补全候选写死在脚本里,而不是回头调 cli.js 取(动态调用慢 + 启动开销大)。
 * 反正补全候选基本不变,新加 subcommand 时升一次包补全也跟着升。
 */

const SUBCOMMANDS = [
  'start',
  'stop',
  'status',
  'list',
  'logs',
  'install',
  'uninstall',
  'attach',
  'kill',
  'completion',
] as const;

const TOP_LEVEL_FLAGS = [
  '--port',
  '--host',
  '--token',
  '--workdir',
  '--cwd',
  '--config',
  '--instance-name',
  '--max-buffer-lines',
  '--session-ttl',
  '--auth-rate-limit',
  '--log-dir',
  '--spawn-timeout',
  '--workdir-allow',
  '--workdir-deny',
  '--no-terminal',
  '--no-color',
  '--no-open',
  '--wait-confirm',
  '--strict-port',
  '--help',
  '--version',
  '-p',
  '-h',
  '-v',
  '-S',
] as const;

const KILL_PATTERNS = ['all'] as const;

const COMPLETION_SHELLS = ['zsh', 'bash', 'fish'] as const;
const COMPLETION_SHELL_SET = new Set<string>(COMPLETION_SHELLS);

export function isSupportedCompletionShell(shell: string): boolean {
  return COMPLETION_SHELL_SET.has(shell);
}

export function listCompletionShells(): readonly string[] {
  return COMPLETION_SHELLS;
}

/**
 * 生成 zsh 补全脚本(_atr 函数 + compdef)。
 *
 * 用法:`atr completion zsh >> ~/.zshrc` 或单文件 `atr completion zsh > ~/.config/zsh/completions/_atr`
 */
function zshScript(): string {
  const subs = SUBCOMMANDS.join(' ');
  const flags = TOP_LEVEL_FLAGS.join(' ');
  const killPats = KILL_PATTERNS.join(' ');
  const completionShells = COMPLETION_SHELLS.join(' ');
  return `# atr completion (zsh)
# Generated by 'atr completion zsh'. Append to ~/.zshrc or place in fpath.

_atr() {
  local -a subs flags
  subs=(${subs})
  flags=(${flags})

  if (( CURRENT == 2 )); then
    _alternative \\
      'subcommands:atr subcommand:(${subs})' \\
      'flags:atr flag:(${flags})'
    return
  fi

  case "\${words[2]}" in
    kill)
      if (( CURRENT == 3 )); then
        compadd ${killPats}
      fi
      ;;
    completion)
      if (( CURRENT == 3 )); then
        compadd ${completionShells}
      fi
      ;;
    *)
      compadd -- $flags
      ;;
  esac
}

compdef _atr atr
`;
}

/**
 * 生成 bash 补全脚本。
 */
function bashScript(): string {
  const subs = SUBCOMMANDS.join(' ');
  const flags = TOP_LEVEL_FLAGS.join(' ');
  const killPats = KILL_PATTERNS.join(' ');
  const completionShells = COMPLETION_SHELLS.join(' ');
  return `# atr completion (bash)
# Generated by 'atr completion bash'. Append to ~/.bashrc or ~/.bash_completion.

_atr_complete() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${subs} ${flags}" -- "$cur") )
    return
  fi

  case "\${COMP_WORDS[1]}" in
    kill)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "${killPats}" -- "$cur") )
        return
      fi
      ;;
    completion)
      if [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "${completionShells}" -- "$cur") )
        return
      fi
      ;;
  esac

  COMPREPLY=( $(compgen -W "${flags}" -- "$cur") )
}

complete -F _atr_complete atr
`;
}

/**
 * 生成 fish 补全脚本。
 */
function fishScript(): string {
  const lines: string[] = [
    '# atr completion (fish)',
    "# Generated by 'atr completion fish'. Append to ~/.config/fish/completions/atr.fish",
    '',
  ];
  for (const sub of SUBCOMMANDS) {
    lines.push(
      `complete -c atr -n '__fish_use_subcommand' -f -a '${sub}'`,
    );
  }
  for (const pat of KILL_PATTERNS) {
    lines.push(`complete -c atr -n '__fish_seen_subcommand_from kill' -f -a '${pat}'`);
  }
  for (const sh of COMPLETION_SHELLS) {
    lines.push(`complete -c atr -n '__fish_seen_subcommand_from completion' -f -a '${sh}'`);
  }
  // 长 flag 在所有上下文都可补,简单 flat 列出
  for (const flag of TOP_LEVEL_FLAGS) {
    if (flag.startsWith('--')) {
      lines.push(`complete -c atr -l '${flag.slice(2)}'`);
    }
  }
  return lines.join('\n') + '\n';
}

export function generateCompletionScript(shell: string): string {
  switch (shell) {
    case 'zsh':
      return zshScript();
    case 'bash':
      return bashScript();
    case 'fish':
      return fishScript();
    default:
      throw new Error(`unsupported shell: ${shell}`);
  }
}
